import type { ContextMeta } from "@/lib/db/schema";

export type AgentPageDraft = {
  title: string;
  icon: string;
  text: string;
};

/** Structured pages the agent creates for launch-style multi-step goals. */
export function buildLaunchPageDrafts(meta: ContextMeta): AgentPageDraft[] {
  const sources = meta.sources.map((s) => `- ${s.title}`).join("\n") || "- (none)";

  return [
    {
      title: "Launch Plan",
      icon: "🎯",
      text: `# Launch Plan

Generated by the workspace agent after SuperCompress-compressed retrieval.

## Objective
Ship OpenPages with SuperCompress as core infrastructure — not a plugin.

## Workstreams
### Engineering
- MCP auth tokens
- Agent edit attribution in version history
- Docker image publish

### Marketing
- Landing page SuperCompress before/after animation
- Demo video
- Launch posts

### Launch day
- Support rotation
- Status page

## Sources (post-compression)
${sources}

## Compression this run
${meta.originalTokens} → ${meta.compressedTokens} tokens (${meta.tokensSavedPct.toFixed(1)}% saved)
`,
    },
    {
      title: "Engineering Checklist",
      icon: "⚙️",
      text: `# Engineering Checklist

- [ ] Finalize MCP auth tokens
- [ ] Verify SuperCompress API + local fallback
- [ ] Version history actor types (user / agent / mcp)
- [ ] Publish Docker image
- [ ] Smoke test: Workspace → Retrieval → SuperCompress → Model
`,
    },
    {
      title: "Marketing Checklist",
      icon: "📣",
      text: `# Marketing Checklist

- [ ] Before/after SuperCompress animation on landing
- [ ] Demo video
- [ ] Blog: "Persistent context without persistent token costs"
- [ ] Community launch posts
`,
    },
    {
      title: "Launch Day Runbook",
      icon: "📅",
      text: `# Launch Day Runbook

## T-0
- [ ] Flip landing CTAs live
- [ ] Post announcement
- [ ] Open support rotation

## During
- Monitor agent errors
- Watch SuperCompress savings in the context inspector
`,
    },
  ];
}

export function shouldCreateLaunchPages(goal: string): boolean {
  const lower = goal.toLowerCase();
  return (
    lower.includes("launch") ||
    lower.includes("create page") ||
    lower.includes("create pages") ||
    lower.includes("plan")
  );
}
